/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClientErrorErrors from './ClientErrorErrors';

/**
 * The ClientError model module.
 * @module model/ClientError
 * @version 1.0.0
 */
class ClientError {
    /**
     * Constructs a new <code>ClientError</code>.
     * @alias module:model/ClientError
     */
    constructor() { 
        
        ClientError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClientError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientError} obj Optional instance to populate.
     * @return {module:model/ClientError} The populated <code>ClientError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientError();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ClientErrorErrors]);
            }
        }
        return obj;
    }

/**
     * @return {Array.<module:model/ClientErrorErrors>}
     */
    getErrors() {
        return this.errors;
    }

    /**
     * @param {Array.<module:model/ClientErrorErrors>} errors
     */
    setErrors(errors) {
        this['errors'] = errors;
    }

}

/**
 * @member {Array.<module:model/ClientErrorErrors>} errors
 */
ClientError.prototype['errors'] = undefined;






export default ClientError;

