/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Event model module.
* @module model/Event
* @version 0.1.0
*/
export default class Event {
    /**
    * Constructs a new <code>Event</code>.
    * @alias module:model/Event
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Event} obj Optional instance to populate.
    * @return {module:model/Event} The populated <code>Event</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Event();

            
            
            

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} _id
    *
    _id = undefined;
    */
    /**
    * @member {Date} createdAt
    *
    createdAt = undefined;
    */
    /**
    * @member {Date} date
    *
    date = undefined;
    */
    /**
    * @member {String} name
    *
    name = undefined;
    */
    /**
    * @member {String} slug
    *
    slug = undefined;
    */
    /**
    * @member {Date} updatedAt
    *
    updatedAt = undefined;
    */





    /**
    * @return {String}
    */
    getId() {
        return this._id;
    }

    /**
    * @param {String} id
    */
    setId(id) {
        this['_id'] = id;
    }

    /**
    * @return {Date}
    */
    getCreatedAt() {
        return this.createdAt;
    }

    /**
    * @param {Date} createdAt
    */
    setCreatedAt(createdAt) {
        this['createdAt'] = createdAt;
    }

    /**
    * @return {Date}
    */
    getDate() {
        return this.date;
    }

    /**
    * @param {Date} _date
    */
    setDate(_date) {
        this['date'] = _date;
    }

    /**
    * @return {String}
    */
    getName() {
        return this.name;
    }

    /**
    * @param {String} name
    */
    setName(name) {
        this['name'] = name;
    }

    /**
    * @return {String}
    */
    getSlug() {
        return this.slug;
    }

    /**
    * @param {String} slug
    */
    setSlug(slug) {
        this['slug'] = slug;
    }

    /**
    * @return {Date}
    */
    getUpdatedAt() {
        return this.updatedAt;
    }

    /**
    * @param {Date} updatedAt
    */
    setUpdatedAt(updatedAt) {
        this['updatedAt'] = updatedAt;
    }




}


