/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The GoogleCalendar model module.
* @module model/GoogleCalendar
* @version 0.1.0
*/
export default class GoogleCalendar {
    /**
    * Constructs a new <code>GoogleCalendar</code>.
    * @alias module:model/GoogleCalendar
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>GoogleCalendar</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GoogleCalendar} obj Optional instance to populate.
    * @return {module:model/GoogleCalendar} The populated <code>GoogleCalendar</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoogleCalendar();

            
            
            

        }
        return obj;
    }









}


