/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsersForgotPasswordData from './UsersForgotPasswordData';

/**
 * The InlineObject7 model module.
 * @module model/InlineObject7
 * @version 1.0.0
 */
class InlineObject7 {
    /**
     * Constructs a new <code>InlineObject7</code>.
     * @alias module:model/InlineObject7
     * @param data {module:model/UsersForgotPasswordData} 
     */
    constructor(data) { 
        
        InlineObject7.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>InlineObject7</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject7} obj Optional instance to populate.
     * @return {module:model/InlineObject7} The populated <code>InlineObject7</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject7();

            if (data.hasOwnProperty('data')) {
                obj['data'] = UsersForgotPasswordData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

/**
     * @return {module:model/UsersForgotPasswordData}
     */
    getData() {
        return this.data;
    }

    /**
     * @param {module:model/UsersForgotPasswordData} data
     */
    setData(data) {
        this['data'] = data;
    }

}

/**
 * @member {module:model/UsersForgotPasswordData} data
 */
InlineObject7.prototype['data'] = undefined;






export default InlineObject7;

