/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Locale model module.
 * @module model/Locale
 * @version 1.0.0
 */
class Locale {
    /**
     * Constructs a new <code>Locale</code>.
     * @alias module:model/Locale
     */
    constructor() { 
        
        Locale.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Locale</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Locale} obj Optional instance to populate.
     * @return {module:model/Locale} The populated <code>Locale</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Locale();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getCode() {
        return this.code;
    }

    /**
     * @param {String} code
     */
    setCode(code) {
        this['code'] = code;
    }
/**
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * @param {String} name
     */
    setName(name) {
        this['name'] = name;
    }

}

/**
 * @member {String} code
 */
Locale.prototype['code'] = undefined;

/**
 * @member {String} name
 */
Locale.prototype['name'] = undefined;






export default Locale;

