/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MeEventPutRequestBody model module.
* @module model/MeEventPutRequestBody
* @version 0.1.0
*/
export default class MeEventPutRequestBody {
    /**
    * Constructs a new <code>MeEventPutRequestBody</code>.
    * @alias module:model/MeEventPutRequestBody
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MeEventPutRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MeEventPutRequestBody} obj Optional instance to populate.
    * @return {module:model/MeEventPutRequestBody} The populated <code>MeEventPutRequestBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeEventPutRequestBody();

            
            
            

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} date
    *
    date = undefined;
    */
    /**
    * @member {String} name
    *
    name = undefined;
    */





    /**
    * @return {Date}
    */
    getDate() {
        return this.date;
    }

    /**
    * @param {Date} _date
    */
    setDate(_date) {
        this['date'] = _date;
    }

    /**
    * @return {String}
    */
    getName() {
        return this.name;
    }

    /**
    * @param {String} name
    */
    setName(name) {
        this['name'] = name;
    }




}


