/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MicrosoftCalendarEventStart from './MicrosoftCalendarEventStart';





/**
* The MicrosoftCalendarEvent model module.
* @module model/MicrosoftCalendarEvent
* @version 0.1.0
*/
export default class MicrosoftCalendarEvent {
    /**
    * Constructs a new <code>MicrosoftCalendarEvent</code>.
    * @alias module:model/MicrosoftCalendarEvent
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MicrosoftCalendarEvent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MicrosoftCalendarEvent} obj Optional instance to populate.
    * @return {module:model/MicrosoftCalendarEvent} The populated <code>MicrosoftCalendarEvent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MicrosoftCalendarEvent();

            
            
            

            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = MicrosoftCalendarEventStart.constructFromObject(data['start']);
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = MicrosoftCalendarEventStart.constructFromObject(data['end']);
            }
        }
        return obj;
    }

    /**
    * @member {String} subject
    *
    subject = undefined;
    */
    /**
    * @member {String} id
    *
    id = undefined;
    */
    /**
    * @member {module:model/MicrosoftCalendarEventStart} start
    *
    start = undefined;
    */
    /**
    * @member {module:model/MicrosoftCalendarEventStart} end
    *
    end = undefined;
    */





    /**
    * @return {String}
    */
    getSubject() {
        return this.subject;
    }

    /**
    * @param {String} subject
    */
    setSubject(subject) {
        this['subject'] = subject;
    }

    /**
    * @return {String}
    */
    getId() {
        return this.id;
    }

    /**
    * @param {String} id
    */
    setId(id) {
        this['id'] = id;
    }

    /**
    * @return {module:model/MicrosoftCalendarEventStart}
    */
    getStart() {
        return this.start;
    }

    /**
    * @param {module:model/MicrosoftCalendarEventStart} start
    */
    setStart(start) {
        this['start'] = start;
    }

    /**
    * @return {module:model/MicrosoftCalendarEventStart}
    */
    getEnd() {
        return this.end;
    }

    /**
    * @param {module:model/MicrosoftCalendarEventStart} end
    */
    setEnd(end) {
        this['end'] = end;
    }




}


