/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MyEventsDataAttributes from './MyEventsDataAttributes';

/**
 * The MyEventsImportData model module.
 * @module model/MyEventsImportData
 * @version 1.0.0
 */
class MyEventsImportData {
    /**
     * Constructs a new <code>MyEventsImportData</code>.
     * @alias module:model/MyEventsImportData
     */
    constructor() { 
        
        MyEventsImportData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MyEventsImportData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MyEventsImportData} obj Optional instance to populate.
     * @return {module:model/MyEventsImportData} The populated <code>MyEventsImportData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MyEventsImportData();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = MyEventsDataAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

/**
     * @return {module:model/MyEventsDataAttributes}
     */
    getAttributes() {
        return this.attributes;
    }

    /**
     * @param {module:model/MyEventsDataAttributes} attributes
     */
    setAttributes(attributes) {
        this['attributes'] = attributes;
    }

}

/**
 * @member {module:model/MyEventsDataAttributes} attributes
 */
MyEventsImportData.prototype['attributes'] = undefined;






export default MyEventsImportData;

