/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MyProfileDataAttributes model module.
 * @module model/MyProfileDataAttributes
 * @version 1.0.0
 */
class MyProfileDataAttributes {
    /**
     * Constructs a new <code>MyProfileDataAttributes</code>.
     * @alias module:model/MyProfileDataAttributes
     */
    constructor() { 
        
        MyProfileDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MyProfileDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MyProfileDataAttributes} obj Optional instance to populate.
     * @return {module:model/MyProfileDataAttributes} The populated <code>MyProfileDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MyProfileDataAttributes();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('preferredMeasurementUnit')) {
                obj['preferredMeasurementUnit'] = ApiClient.convertToType(data['preferredMeasurementUnit'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * @param {String} email
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * @return {String}
     */
    getFirstName() {
        return this.firstName;
    }

    /**
     * @param {String} firstName
     */
    setFirstName(firstName) {
        this['firstName'] = firstName;
    }
/**
     * @return {String}
     */
    getLastName() {
        return this.lastName;
    }

    /**
     * @param {String} lastName
     */
    setLastName(lastName) {
        this['lastName'] = lastName;
    }
/**
     * @return {String}
     */
    getPreferredMeasurementUnit() {
        return this.preferredMeasurementUnit;
    }

    /**
     * @param {String} preferredMeasurementUnit
     */
    setPreferredMeasurementUnit(preferredMeasurementUnit) {
        this['preferredMeasurementUnit'] = preferredMeasurementUnit;
    }

}

/**
 * @member {String} email
 */
MyProfileDataAttributes.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
MyProfileDataAttributes.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
MyProfileDataAttributes.prototype['lastName'] = undefined;

/**
 * @member {String} preferredMeasurementUnit
 */
MyProfileDataAttributes.prototype['preferredMeasurementUnit'] = undefined;






export default MyProfileDataAttributes;

