/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ResetPasswordPostRequestBody model module.
* @module model/ResetPasswordPostRequestBody
* @version 0.1.0
*/
export default class ResetPasswordPostRequestBody {
    /**
    * Constructs a new <code>ResetPasswordPostRequestBody</code>.
    * @alias module:model/ResetPasswordPostRequestBody
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ResetPasswordPostRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ResetPasswordPostRequestBody} obj Optional instance to populate.
    * @return {module:model/ResetPasswordPostRequestBody} The populated <code>ResetPasswordPostRequestBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResetPasswordPostRequestBody();

            
            
            

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('passwordConfirmation')) {
                obj['passwordConfirmation'] = ApiClient.convertToType(data['passwordConfirmation'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} password
    *
    password = undefined;
    */
    /**
    * @member {String} passwordConfirmation
    *
    passwordConfirmation = undefined;
    */
    /**
    * @member {String} code
    *
    code = undefined;
    */





    /**
    * @return {String}
    */
    getPassword() {
        return this.password;
    }

    /**
    * @param {String} password
    */
    setPassword(password) {
        this['password'] = password;
    }

    /**
    * @return {String}
    */
    getPasswordConfirmation() {
        return this.passwordConfirmation;
    }

    /**
    * @param {String} passwordConfirmation
    */
    setPasswordConfirmation(passwordConfirmation) {
        this['passwordConfirmation'] = passwordConfirmation;
    }

    /**
    * @return {String}
    */
    getCode() {
        return this.code;
    }

    /**
    * @param {String} code
    */
    setCode(code) {
        this['code'] = code;
    }




}


