/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SessionsDataAttributes model module.
 * @module model/SessionsDataAttributes
 * @version 1.0.0
 */
class SessionsDataAttributes {
    /**
     * Constructs a new <code>SessionsDataAttributes</code>.
     * @alias module:model/SessionsDataAttributes
     * @param email {String} 
     * @param password {String} 
     */
    constructor(email, password) { 
        
        SessionsDataAttributes.initialize(this, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password) { 
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>SessionsDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SessionsDataAttributes} obj Optional instance to populate.
     * @return {module:model/SessionsDataAttributes} The populated <code>SessionsDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionsDataAttributes();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * @param {String} email
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * @return {String}
     */
    getPassword() {
        return this.password;
    }

    /**
     * @param {String} password
     */
    setPassword(password) {
        this['password'] = password;
    }

}

/**
 * @member {String} email
 */
SessionsDataAttributes.prototype['email'] = undefined;

/**
 * @member {String} password
 */
SessionsDataAttributes.prototype['password'] = undefined;






export default SessionsDataAttributes;

