/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SessionsDataAttributes from './SessionsDataAttributes';

/**
 * The SessionsData model module.
 * @module model/SessionsData
 * @version 1.0.0
 */
class SessionsData {
    /**
     * Constructs a new <code>SessionsData</code>.
     * @alias module:model/SessionsData
     * @param attributes {module:model/SessionsDataAttributes} 
     */
    constructor(attributes) { 
        
        SessionsData.initialize(this, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributes) { 
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>SessionsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SessionsData} obj Optional instance to populate.
     * @return {module:model/SessionsData} The populated <code>SessionsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionsData();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = SessionsDataAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

/**
     * @return {module:model/SessionsDataAttributes}
     */
    getAttributes() {
        return this.attributes;
    }

    /**
     * @param {module:model/SessionsDataAttributes} attributes
     */
    setAttributes(attributes) {
        this['attributes'] = attributes;
    }

}

/**
 * @member {module:model/SessionsDataAttributes} attributes
 */
SessionsData.prototype['attributes'] = undefined;






export default SessionsData;

