/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersDataAttributes model module.
 * @module model/UsersDataAttributes
 * @version 1.0.0
 */
class UsersDataAttributes {
    /**
     * Constructs a new <code>UsersDataAttributes</code>.
     * @alias module:model/UsersDataAttributes
     * @param email {String} 
     * @param firstName {String} 
     */
    constructor(email, firstName) { 
        
        UsersDataAttributes.initialize(this, email, firstName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, firstName) { 
        obj['email'] = email;
        obj['firstName'] = firstName;
    }

    /**
     * Constructs a <code>UsersDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersDataAttributes} obj Optional instance to populate.
     * @return {module:model/UsersDataAttributes} The populated <code>UsersDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersDataAttributes();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * @param {String} email
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * @return {String}
     */
    getFirstName() {
        return this.firstName;
    }

    /**
     * @param {String} firstName
     */
    setFirstName(firstName) {
        this['firstName'] = firstName;
    }
/**
     * @return {String}
     */
    getLastName() {
        return this.lastName;
    }

    /**
     * @param {String} lastName
     */
    setLastName(lastName) {
        this['lastName'] = lastName;
    }

}

/**
 * @member {String} email
 */
UsersDataAttributes.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
UsersDataAttributes.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
UsersDataAttributes.prototype['lastName'] = undefined;






export default UsersDataAttributes;

