/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClientError from '../model/ClientError';
import InlineResponse2003 from '../model/InlineResponse2003';

/**
* Translations service.
* @module api/TranslationsApi
* @version 1.0.0
*/
export default class TranslationsApi {

    /**
    * Constructs a new TranslationsApi. 
    * @alias module:api/TranslationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List translations by locale code
     * List translations by locale code
     * @param {module:model/String} localeCode Locale code of translations
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2003} and HTTP response
     */
    listTranslationsByLocaleWithHttpInfo(localeCode) {
      let postBody = null;
      // verify the required parameter 'localeCode' is set
      if (localeCode === undefined || localeCode === null) {
        throw new Error("Missing the required parameter 'localeCode' when calling listTranslationsByLocale");
      }

      let pathParams = {
        'localeCode': localeCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/vnd.api+json'];
      let returnType = InlineResponse2003;
      return this.apiClient.callApi(
        '/locales/{localeCode}/translations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List translations by locale code
     * List translations by locale code
     * @param {module:model/String} localeCode Locale code of translations
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2003}
     */
    listTranslationsByLocale(localeCode) {
      return this.listTranslationsByLocaleWithHttpInfo(localeCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
