/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocketJsSdk);
  }
}(this, function(expect, DocketJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocketJsSdk.GoogleCalendarList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GoogleCalendarList', function() {
    it('should create an instance of GoogleCalendarList', function() {
      // uncomment below and update the code to test GoogleCalendarList
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be.a(DocketJsSdk.GoogleCalendarList);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be();
    });

    it('should have the property timeZone (base name: "timeZone")', function() {
      // uncomment below and update the code to test the property timeZone
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be();
    });

    it('should have the property backgroundColor (base name: "backgroundColor")', function() {
      // uncomment below and update the code to test the property backgroundColor
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be();
    });

    it('should have the property foregroundColor (base name: "foregroundColor")', function() {
      // uncomment below and update the code to test the property foregroundColor
      //var instane = new DocketJsSdk.GoogleCalendarList();
      //expect(instance).to.be();
    });

  });

}));
