/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ClientError from './model/ClientError';
import ClientErrorErrors from './model/ClientErrorErrors';
import Event from './model/Event';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineObject6 from './model/InlineObject6';
import InlineObject7 from './model/InlineObject7';
import InlineObject8 from './model/InlineObject8';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2001Data from './model/InlineResponse2001Data';
import InlineResponse2001DataAttributes from './model/InlineResponse2001DataAttributes';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2002Data from './model/InlineResponse2002Data';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2003Data from './model/InlineResponse2003Data';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2005Data from './model/InlineResponse2005Data';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2006Data from './model/InlineResponse2006Data';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2008Data from './model/InlineResponse2008Data';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse2009Data from './model/InlineResponse2009Data';
import InlineResponse200Data from './model/InlineResponse200Data';
import InlineResponse200DataAttributes from './model/InlineResponse200DataAttributes';
import InlineResponse200Links from './model/InlineResponse200Links';
import Locale from './model/Locale';
import MyEventsData from './model/MyEventsData';
import MyEventsDataAttributes from './model/MyEventsDataAttributes';
import MyEventsImportData from './model/MyEventsImportData';
import MyProfileData from './model/MyProfileData';
import MyProfileDataAttributes from './model/MyProfileDataAttributes';
import Session from './model/Session';
import SessionsData from './model/SessionsData';
import SessionsDataAttributes from './model/SessionsDataAttributes';
import Translation from './model/Translation';
import User from './model/User';
import UsersConfirmRegistrationData from './model/UsersConfirmRegistrationData';
import UsersConfirmRegistrationDataAttributes from './model/UsersConfirmRegistrationDataAttributes';
import UsersData from './model/UsersData';
import UsersDataAttributes from './model/UsersDataAttributes';
import UsersForgotPasswordData from './model/UsersForgotPasswordData';
import UsersForgotPasswordDataAttributes from './model/UsersForgotPasswordDataAttributes';
import DocsApi from './api/DocsApi';
import EventsApi from './api/EventsApi';
import GoogleApi from './api/GoogleApi';
import HealthCheckApi from './api/HealthCheckApi';
import LocalesApi from './api/LocalesApi';
import MicrosoftApi from './api/MicrosoftApi';
import SearchApi from './api/SearchApi';
import SessionsApi from './api/SessionsApi';
import TranslationsApi from './api/TranslationsApi';
import UsersApi from './api/UsersApi';


/**
* JavaScript SDK for interfacing with the Docket API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DocketJs = require('index'); // See note below*.
* var xxxSvc = new DocketJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DocketJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DocketJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DocketJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ClientError model constructor.
     * @property {module:model/ClientError}
     */
    ClientError,

    /**
     * The ClientErrorErrors model constructor.
     * @property {module:model/ClientErrorErrors}
     */
    ClientErrorErrors,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineObject7 model constructor.
     * @property {module:model/InlineObject7}
     */
    InlineObject7,

    /**
     * The InlineObject8 model constructor.
     * @property {module:model/InlineObject8}
     */
    InlineObject8,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001Data model constructor.
     * @property {module:model/InlineResponse2001Data}
     */
    InlineResponse2001Data,

    /**
     * The InlineResponse2001DataAttributes model constructor.
     * @property {module:model/InlineResponse2001DataAttributes}
     */
    InlineResponse2001DataAttributes,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002Data model constructor.
     * @property {module:model/InlineResponse2002Data}
     */
    InlineResponse2002Data,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2003Data model constructor.
     * @property {module:model/InlineResponse2003Data}
     */
    InlineResponse2003Data,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2005Data model constructor.
     * @property {module:model/InlineResponse2005Data}
     */
    InlineResponse2005Data,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2006Data model constructor.
     * @property {module:model/InlineResponse2006Data}
     */
    InlineResponse2006Data,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2008Data model constructor.
     * @property {module:model/InlineResponse2008Data}
     */
    InlineResponse2008Data,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse2009Data model constructor.
     * @property {module:model/InlineResponse2009Data}
     */
    InlineResponse2009Data,

    /**
     * The InlineResponse200Data model constructor.
     * @property {module:model/InlineResponse200Data}
     */
    InlineResponse200Data,

    /**
     * The InlineResponse200DataAttributes model constructor.
     * @property {module:model/InlineResponse200DataAttributes}
     */
    InlineResponse200DataAttributes,

    /**
     * The InlineResponse200Links model constructor.
     * @property {module:model/InlineResponse200Links}
     */
    InlineResponse200Links,

    /**
     * The Locale model constructor.
     * @property {module:model/Locale}
     */
    Locale,

    /**
     * The MyEventsData model constructor.
     * @property {module:model/MyEventsData}
     */
    MyEventsData,

    /**
     * The MyEventsDataAttributes model constructor.
     * @property {module:model/MyEventsDataAttributes}
     */
    MyEventsDataAttributes,

    /**
     * The MyEventsImportData model constructor.
     * @property {module:model/MyEventsImportData}
     */
    MyEventsImportData,

    /**
     * The MyProfileData model constructor.
     * @property {module:model/MyProfileData}
     */
    MyProfileData,

    /**
     * The MyProfileDataAttributes model constructor.
     * @property {module:model/MyProfileDataAttributes}
     */
    MyProfileDataAttributes,

    /**
     * The Session model constructor.
     * @property {module:model/Session}
     */
    Session,

    /**
     * The SessionsData model constructor.
     * @property {module:model/SessionsData}
     */
    SessionsData,

    /**
     * The SessionsDataAttributes model constructor.
     * @property {module:model/SessionsDataAttributes}
     */
    SessionsDataAttributes,

    /**
     * The Translation model constructor.
     * @property {module:model/Translation}
     */
    Translation,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UsersConfirmRegistrationData model constructor.
     * @property {module:model/UsersConfirmRegistrationData}
     */
    UsersConfirmRegistrationData,

    /**
     * The UsersConfirmRegistrationDataAttributes model constructor.
     * @property {module:model/UsersConfirmRegistrationDataAttributes}
     */
    UsersConfirmRegistrationDataAttributes,

    /**
     * The UsersData model constructor.
     * @property {module:model/UsersData}
     */
    UsersData,

    /**
     * The UsersDataAttributes model constructor.
     * @property {module:model/UsersDataAttributes}
     */
    UsersDataAttributes,

    /**
     * The UsersForgotPasswordData model constructor.
     * @property {module:model/UsersForgotPasswordData}
     */
    UsersForgotPasswordData,

    /**
     * The UsersForgotPasswordDataAttributes model constructor.
     * @property {module:model/UsersForgotPasswordDataAttributes}
     */
    UsersForgotPasswordDataAttributes,

    /**
    * The DocsApi service constructor.
    * @property {module:api/DocsApi}
    */
    DocsApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The GoogleApi service constructor.
    * @property {module:api/GoogleApi}
    */
    GoogleApi,

    /**
    * The HealthCheckApi service constructor.
    * @property {module:api/HealthCheckApi}
    */
    HealthCheckApi,

    /**
    * The LocalesApi service constructor.
    * @property {module:api/LocalesApi}
    */
    LocalesApi,

    /**
    * The MicrosoftApi service constructor.
    * @property {module:api/MicrosoftApi}
    */
    MicrosoftApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The SessionsApi service constructor.
    * @property {module:api/SessionsApi}
    */
    SessionsApi,

    /**
    * The TranslationsApi service constructor.
    * @property {module:api/TranslationsApi}
    */
    TranslationsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
