/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocketJs);
  }
}(this, function(expect, DocketJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocketJs.GoogleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GoogleApi', function() {
    describe('getGoogleOAuthUrl', function() {
      it('should call getGoogleOAuthUrl successfully', function(done) {
        //uncomment below and update the code to test getGoogleOAuthUrl
        //instance.getGoogleOAuthUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleGetAccessTokens', function() {
      it('should call googleGetAccessTokens successfully', function(done) {
        //uncomment below and update the code to test googleGetAccessTokens
        //instance.googleGetAccessTokens(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleListCalendarLists', function() {
      it('should call googleListCalendarLists successfully', function(done) {
        //uncomment below and update the code to test googleListCalendarLists
        //instance.googleListCalendarLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleListEventInstances', function() {
      it('should call googleListEventInstances successfully', function(done) {
        //uncomment below and update the code to test googleListEventInstances
        //instance.googleListEventInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleListEventsByCalendarId', function() {
      it('should call googleListEventsByCalendarId successfully', function(done) {
        //uncomment below and update the code to test googleListEventsByCalendarId
        //instance.googleListEventsByCalendarId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleShowCalendarById', function() {
      it('should call googleShowCalendarById successfully', function(done) {
        //uncomment below and update the code to test googleShowCalendarById
        //instance.googleShowCalendarById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleShowCalendarListById', function() {
      it('should call googleShowCalendarListById successfully', function(done) {
        //uncomment below and update the code to test googleShowCalendarListById
        //instance.googleShowCalendarListById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleShowEventById', function() {
      it('should call googleShowEventById successfully', function(done) {
        //uncomment below and update the code to test googleShowEventById
        //instance.googleShowEventById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleWatchCalendarLists', function() {
      it('should call googleWatchCalendarLists successfully', function(done) {
        //uncomment below and update the code to test googleWatchCalendarLists
        //instance.googleWatchCalendarLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('googleWatchEvents', function() {
      it('should call googleWatchEvents successfully', function(done) {
        //uncomment below and update the code to test googleWatchEvents
        //instance.googleWatchEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
