/**
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@DocketDocketSdk);
  }
}(this, function(expect, @DocketDocketSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @DocketDocketSdk.MeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MeApi', function() {
    describe('meDelete', function() {
      it('should call meDelete successfully', function(done) {
        //uncomment below and update the code to test meDelete
        //instance.meDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('meEventsGet', function() {
      it('should call meEventsGet successfully', function(done) {
        //uncomment below and update the code to test meEventsGet
        //instance.meEventsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('meEventsIdDelete', function() {
      it('should call meEventsIdDelete successfully', function(done) {
        //uncomment below and update the code to test meEventsIdDelete
        //instance.meEventsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('meEventsIdPut', function() {
      it('should call meEventsIdPut successfully', function(done) {
        //uncomment below and update the code to test meEventsIdPut
        //instance.meEventsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('meEventsPost', function() {
      it('should call meEventsPost successfully', function(done) {
        //uncomment below and update the code to test meEventsPost
        //instance.meEventsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('meGet', function() {
      it('should call meGet successfully', function(done) {
        //uncomment below and update the code to test meGet
        //instance.meGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mePut', function() {
      it('should call mePut successfully', function(done) {
        //uncomment below and update the code to test mePut
        //instance.mePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
