/**
 * Docket API
 * Docket API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@docket.fyi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocketJs);
  }
}(this, function(expect, DocketJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocketJs.MicrosoftApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MicrosoftApi', function() {
    describe('getMicrosoftOAuthUrl', function() {
      it('should call getMicrosoftOAuthUrl successfully', function(done) {
        //uncomment below and update the code to test getMicrosoftOAuthUrl
        //instance.getMicrosoftOAuthUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('microsoftGetAccessTokens', function() {
      it('should call microsoftGetAccessTokens successfully', function(done) {
        //uncomment below and update the code to test microsoftGetAccessTokens
        //instance.microsoftGetAccessTokens(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('microsoftListCalendars', function() {
      it('should call microsoftListCalendars successfully', function(done) {
        //uncomment below and update the code to test microsoftListCalendars
        //instance.microsoftListCalendars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('microsoftListEventsByCalendarId', function() {
      it('should call microsoftListEventsByCalendarId successfully', function(done) {
        //uncomment below and update the code to test microsoftListEventsByCalendarId
        //instance.microsoftListEventsByCalendarId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
